# Generated by Django 3.1.4 on 2021-01-01 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0002_auto_20210101_2020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='contact',
            new_name='Contact',
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='Address',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='Name',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='portfolio_site',
            field=models.URLField(blank=True),
        ),
    ]
